Repository mikedelgaudio/CS-555-GEDCOM, pull requests merged in 2020-06, with the labels that each got.

#21 Added a Makefile for use with testing
  makefile
Labels: PyTest

#30 Update for README style guide
  README.md
Labels: documentation

#32 US01 - Date After Current Date Helper Function Added
  README.md
  src/helpers/dates.py
  src/main.py
  tests/gedcom_test.py
Labels: DUE NEXT

#61 US29 - List Deceased Complete
  src/main.py
  src/modules/list_deceased.py
  tests/gedcom_test.py
Labels: DUE NEXT

#62 US22 - Unique IDs
  src/main.py
  src/modules/unique_id.py
  test.ged
  tests/gedcom_test.py
Labels: DUE NEXT
